version: '2'

services:

  redis-admin:
    image: actency/docker-phpredisadmin
    links:
      - redis:redis
    ports:
      - 8080:80
    environment:
      - REDIS_1_HOST=redis

  hydra:
    image: oryd/hydra
    links:
     - redis:redis
    ports:
      - "4444:4444"
      - "4445:4445"
    # Uncomment when domain and ssl certs are ready
    # volumes:
    #   - ./ssl:/etc/hydra/ssl
    environment:
      - LOG_LEVEL=debug
      - SYSTEM_SECRET=systemsecrethere
      - DATABASE_URL=redis://redis:6379/0
      - FORCE_ROOT_CLIENT_CREDENTIALS=admin:demo-password
      - ACCESS_TOKEN_LIFESPAN=1440h # 60 days
      # Uncomment when domain and ssl certs are ready
      # - HTTPS_TLS_CERT_PATH=/etc/hydra/ssl/cert.pem
      # - HTTPS_TLS_KEY_PATH=/etc/hydra/ssl/key.pem
    restart: unless-stopped

  redis:
    image: redis
    ports:
      - 6379:6379
    volumes:
      - ./docker_data/redis_data:/data
