version: '2'

services:

  redis-admin:
    image: actency/docker-phpredisadmin
    links:
      - redis:redis
    ports:
      - 9001:80
    environment:
      - REDIS_1_HOST=redis

  hydra:
    image: oryd/hydra
    links:
     - redis:redis
    ports:
      - "4444:4444"
      - "4445:4445"
    # Uncomment when domain and ssl certs are ready
    # volumes:
    #   - ./ssl:/etc/hydra/ssl
    environment:
      - LOG_LEVEL=debug
      - SYSTEM_SECRET=systemsecrethere
      - DATABASE_URL=redis://redis:6379/0
      - FORCE_ROOT_CLIENT_CREDENTIALS=admin:demo-password
      - ACCESS_TOKEN_LIFESPAN=1440h # 60 days
      # Uncomment when domain and ssl certs are ready
      # - HTTPS_TLS_CERT_PATH=/etc/hydra/ssl/cert.pem
      # - HTTPS_TLS_KEY_PATH=/etc/hydra/ssl/key.pem
    restart: unless-stopped

  proxy:
    image: golang:1.8
    hostname: proxy.axial.net
    ports:
      - 8080:8080
    volumes:
      - "$GOPATH:/go"
      - "./goproxy:/app"
    working_dir: /app/
    extra_hosts:
      blue-api.axial.net: 10.0.0.13
    links:
      - hydra:hydra
    command: sh -c 'go get github.com/pilu/fresh && fresh -c fresh.conf'

  nginx:
    image: nginx
    depends_on:
      - proxy
    ports:
      - 80:80
      - 443:443
      - 30443:30443
    links:
      - proxy:proxy
    volumes:
      - "./goproxy/default.conf:/etc/nginx/conf.d/default.conf"
      - "./ssl:/etc/nginx/ssl"

  redis:
    image: redis
    ports:
      - 6379:6379
    volumes:
      - ./docker_data/redis_data:/data
